version: "3"
services:
  node-service:
    container_name: node-service
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PORT=${DB_PORT}
    command: npm run dev
  flask-service:
    container_name: flask-service
    build: ./shotping_flask
    restart: always
    ports:
      - 5001:5000
    volumes:
      - ./shotping_flask:/app
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db-data:
