version: "3"
services:
  node-service:
    container_name: node-service
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PORT=${DB_PORT}
    command: npm run dev
  flask-service:
    container_name: flask-service
    build: ./shotping_flask
    restart: always
    ports:
      - 5001:5000
    volumes:
      - ./shotping_flask:/app
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    restart: unless-stopped # 컨테이너 종료시 (재시작여부) 종료 코드와 상관없이 컨테이너가 다시시작하지만 서비스가 중지되거나 제거되면 다시 시작을 중지
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    ports:
      - 5672:5672 #rabbitmq AMQP 기본 포트 번호
      - 15672:15672 #Rabbitmq web
  celery:
    build: ./shotping_flask
    volumes:
      - ./shotping_flask:/code
    depends_on:
      - rabbitmq
    command: celery -A tasks worker --loglevel=info
volumes:
  db-data:
