# ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:8.8.2

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu