groups:
- name: example
  rules:
  # cpu 사용량 80% 이상일 때
  - alert: HighCPU
    expr: 100 - (avg by(instance)(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: High CPU usage

  # 메모리 사용량 80% 이상일 때
  - alert: HighMemory
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: High Memory usage

  # 0.5초 이상 요청 지연이 될 때
  - alert: HighRequestLatency
    expr: job:request_latency_seconds:mean5m{job="node-service"} > 0.5
    for: 2m
    labels:
      severity: page
    annotations:
      summary: High request latency in node-service

  # 서비스가 다운됐을 때
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: Instance {{ $labels.instance }} down