name: SHOTPING Docker CD

on:
  pull_request:
    types:
      - closed
    branches: [main, develop]

jobs:
  cd:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Node service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./shotping_node
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shotping_node:latest

      - name: Build and push flask service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./shotping_flask
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shotping_flask:latest

      - name: Execute remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd SHOTPING-backend
            git pull
            echo "${{ secrets.ENV }}" > .env
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/shotping_node:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/shotping_flask:latest
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up -d
