name: SHOTPING Docker CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build: #Job 이름
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }} # github에 등록한 환경변수
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

        # mysql 컨테이너 연결 확인
      - name: Verify MySQL connection
        run: |
          mysql --version 
          mysql --host 127.0.0.1 --port 3306 -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setting .env
        run: |
          echo "${{ secrets.ENV }}" >> .env 
          cat .env

      - name: Install Node.js dependencies
        run: |
          cd shotping_node
          npm install

      - name: Run Node.js tests
        run: |
          cd shotping_node
          npm test
        env:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: ${{ secrets.MYSQL_USER }}
          DB_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
